//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MvcTrello
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.board = new HashSet<board>();
            this.task = new HashSet<task>();
            this.board1 = new HashSet<board>();
            this.task1 = new HashSet<task>();
        }
        [Key]
        public int idUser { get; set; }
        [Required(ErrorMessage = "Potrebno je unijeti username")]
        public string username { get; set; }
        [Required(ErrorMessage = "Potrebno je unijeti sifru")]
        [StringLength(8, MinimumLength = 2, ErrorMessage = "Sifra treba imati izmedju 2 i 8 znakova")]
        public string password { get; set; }

        [Required(ErrorMessage = "Unesite datum u formatu dd/MM/yyyy")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime creationDate { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<board> board { get; set; }
        public virtual ICollection<task> task { get; set; }
        public virtual ICollection<board> board1 { get; set; }
        public virtual ICollection<task> task1 { get; set; }
    }
}
