//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace MvcTrello
{
    using System;
    using System.Collections.Generic;

    public partial class user
    {
        public user()
        {
            this.board = new HashSet<board>();
            this.task = new HashSet<task>();
            this.board1 = new HashSet<board>();
            this.task1 = new HashSet<task>();
        }
        [Key]
        public int idUser { get; set; }
        [Required(ErrorMessage = "Potrebno je unijeti username", AllowEmptyStrings = false)]
        public string username { get; set; }
        [Required(ErrorMessage = "Potrebno je unijeti sifru", AllowEmptyStrings = false)]
        [StringLength(16, MinimumLength = 5, ErrorMessage = "Sifra treba imati najmanje 5 znakova")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string password { get; set; }
        [Compare("password", ErrorMessage = "Sifre se ne poklapaju")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Unesite datum u formatu dd/MM/yyyy")]
        // [DataType(DataType.Date)]
        // [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime creationDate { get; set; }

        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
                    ErrorMessage = "Potrebno je unijeti validnu E-mail adresu")]
        public string email { get; set; }

        public virtual ICollection<board> board { get; set; }
        public virtual ICollection<task> task { get; set; }
        public virtual ICollection<board> board1 { get; set; }
        public virtual ICollection<task> task1 { get; set; }
    }
}
