//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trollo
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public task()
        {

        }

        public task(int _id, string _title, int _ownerList)
        {
            idTask = _id;
            title = _title;
            ownerList = _ownerList;
        }


        public int idTask { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string comment { get; set; }
        public Nullable<int> label { get; set; }
        public byte[] file { get; set; }
        public int ownerList { get; set; }
        public int taskCreator { get; set; }
        public Nullable<int> taskOwner { get; set; }
    
        public virtual list list { get; set; }
    }
}
