//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trollo
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {

        public user()
        {

        }

        public user(string _username)
        {
            username = _username;
        }

        public user(int _registered, string _username, string _password, string _email)
        {
            registered = _registered;
            username = _username;
            password = _password;
            email = _email;
        }

        public user(string _username, string _email)
        {
            username = _username;
            email = _email;
        }

    
        public int idUser { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime creationDate { get; set; }
        public string email { get; set; }
        public Nullable<int> registered { get; set; }
        public string picture { get; set; }
    
        public virtual ICollection<board> board { get; set; }
    }
}
