//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trollo
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.board = new HashSet<board>();
            this.board1 = new HashSet<board>();
        }


        public user(string _username, string _password)
        {
            username = _username;
            password = _password;
        }

        public user(string _username)
        {
            username = _username;
        }

        public user(string _username, string _password, System.DateTime _creationDate, string _email, string _picture)
        {
            username = _username;
            password = _password;
            creationDate = _creationDate;
            email = _email;
            picture = _picture;
        }
    
        public int idUser { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime creationDate { get; set; }
        public string email { get; set; }
        public Nullable<int> registered { get; set; }
        public string picture { get; set; }
    
        public virtual ICollection<board> board { get; set; }
        public virtual ICollection<board> board1 { get; set; }
    }
}
