//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trollo
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            //new user(0, username, pass, email);
        }
        public user(int id, string _username, string _pass, string _email)
        {
            registered = id;
            username = _username;
            password = _pass;
            email = _email;
        }
    
        public int idUser { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime creationDate { get; set; }
        public string email { get; set; }
        public Nullable<int> registered { get; set; }
        public string picture { get; set; }
    
        public virtual ICollection<board> board { get; set; }
    }
}
