//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcTrollo
{
    using System;
    using System.Collections.Generic;
    
    public partial class board
    {
        public board()
        {
            this.list = new HashSet<list>();
            this.user1 = new HashSet<user>();
        }
    
        public int idBoard { get; set; }
        public string title { get; set; }
        public System.DateTime creationDate { get; set; }
        public int boardOwner { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<list> list { get; set; }
        public virtual ICollection<user> user1 { get; set; }
    }
}
